export const POST_MILESTONE = 'POST_MILESTONE';
export const POST_MILESTONE_SUCCESS = 'POST_MILESTONE_SUCCESS';
export const POST_MILESTONE_ERROR = 'POST_MILESTONE_ERROR';
export const DELETE_MILESTONE = 'DELETE_MILESTONE';
export const DELETE_MILESTONE_SUCCESS = 'DELETE_MILESTONE_SUCCESS';
export const DELETE_MILESTONE_ERROR = 'DELETE_MILESTONE_ERROR';